name: Complex-flow
on:
  push:
    branches: [ main ] 
  workflow_dispatch:

jobs:
    job1:
      name: First Job
      runs-on : ubuntu-latest
      steps:
      - name: Print Date Ubuntu
        run: date
    job2:
      name: Second Job
      runs-on: windows-latest
      steps:
      - name: Print date windows
        run: Date
    job3:
      name: Third Job
      runs-on: macos-latest
      steps:
      - name: Print Date MacOS
        run: date
    job4:
      name: Fourth Job
      runs-on: windows-2016
      needs: [job1, job2, job3]
      steps:
      - name: Print date windows 2016
        run: Date
