name: Complex-flow
on:
  push:
    branches: [ main ] 
  workflow_dispatch:

jobs:
    ubuntu:
      name: First Job
      runs-on : ubuntu-latest
      steps:
      - name: Print Date Ubuntu
        run: date
    windows:
      name: Second Job
      runs-on: windows-latest
      steps:
      - name: Print date windows
        run: Date
    macOs:
      name: Third Job
      runs-on: macos-latest
      steps:
      - name: Print Date MacOS
        run: date
    depends:
      name: Fourth Job
      runs-on: windows-2016
      needs: [ubuntu, windows, macOs]
      steps:
      - name: Print date windows 2016
        run: Date
